services:
  # このサービス（プログラム）の設定
  - type: cron
    name: ai-contents-bot
    # ★★★ ここで「Python環境」を明示的に指定します ★★★
    env: python
    region: singapore
    schedule: "*/15 * * * *"
    buildCommand: "python3 -m pip install -r requirements.txt"
    startCommand: "python3 main.py"
