services:
  - type: cron
    name: ai-contents-bot
    env: python
    region: oregon
    schedule: "*/15 * * * *"
    
    # buildCommandは何もしないように設定
    buildCommand: "echo 'Build step is skipped, installing in start command'"
    
    # ★★★★★ 実行コマンドを修正 ★★★★★
    # ライブラリのインストールとプログラム実行を一度に行う
    startCommand: "pip3 install -r requirements.txt && python3 main.py"
