services:
  # このサービス（プログラム）の設定
  - type: cron
    name: ai-contents-bot
    env: python
    # ★★★ リージョンを以前の設定に合わせて修正 ★★★
    region: oregon 
    schedule: "*/15 * * * *"
    buildCommand: "python3 -m pip install -r requirements.txt"
    startCommand: "python3 main.py"
